# .bashrc

# Source library file
[ -f "${LIBRARY_FILE}" ] &&
	. "${LIBRARY_FILE}" ||
	printf "LIBRARY_FILE does not exist"

source_file "${shellrc_file}"

# https://www.computerhope.com/unix/bash/shopt.htm
shopt -s autocd
shopt -s cdspell
shopt -s extglob
shopt -s histappend

# C-x C-h to open man page for currently typed command
# Taken from: https://github.com/Jorengarenar/dotfiles/blob/master/bashrc
bind -x '"\C-x\C-h":man_shortcut'
man_shortcut() {
	man $(echo $READLINE_LINE | awk '{print $1}');
}
