# .cshrc

# Source library file
[ -f "${LIBRARY_FILE}" ] &&
	. "${LIBRARY_FILE}" ||
	printf "LIBRARY_FILE does not exist"

source_file "${shellrc_file}"

set autolist = ambiguous
set complete = enhance
