# .cshrc

# Source library file
[ -f "${LIBRARY_FILE}" ] &&
	. "${LIBRARY_FILE}" ||
	printf "LIBRARY_FILE is unset or null"

set autolist = ambiguous
set complete = enhance

source_file "${shellrc_file}"
