#!/bin/sh

# ~/.xinitrc

# Source library file
if [ ! -f "${LIBRARY_FILE}" ]; then
	printf "LIBRARY_FILE[%s] does not exist\n" "${LIBRARY_FILE}"
	return
fi
. "${LIBRARY_FILE}"

# Set Xmodmap if file exists
if [ -f "$HOME/.Xmodmap" ]; then
	xmodmap "$HOME/.Xmodmap" || log_func "ERROR: xmodmap ~/.Xmodmap in .xinitrc"
fi
# Run xrdb to load .Xresources if file exists
if [ -f "$HOME/.Xresources" ]; then
	xrdb -merge "$HOME/.Xresources" ||
		log_func "ERROR: xrdb -merge ~/.Xresources in .xinitrc"
fi

exec startxfce4
