# .xinitrc

# Source library file
[ -e "${LIBRARY_FILE}" ] || { printf "LIBRARY_FILE is unset or null"; exit 1; }
. "${LIBRARY_FILE}"

# Set Wallpaper
feh --no-fehbg --bg-fill --recursive --randomize $wallpaper_dir &

# Set Xmodmap if file exists
[ -f $HOME/.Xmodmap ] && xmodmap $HOME/.Xmodmap
# Run xrdb to load .Xresources if file exists
[ -f $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources

# Start Window Manager
exec "${window_manager}"
